name: Cypress Tests

on:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./client
    steps:
      # Checkout the Repo
      - uses: actions/checkout@v2

      # Install Node 12
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12

      # Install dependencies
      - run: npm install

      # Run tests
      - run: npm test