name: Cypress Tests

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: run build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          command: build
  tests:
    name: run ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cypress-io/github-action@v4
        with:
          command: test